# Generated by Django 4.1.3 on 2022-11-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9000)),
                ('location', models.CharField(max_length=9000)),
                ('country', models.CharField(max_length=9000)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circuit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9000, unique=True)),
                ('nationality', models.CharField(max_length=9000)),
            ],
            options={
                'db_table': 'constructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=9000)),
                ('surname', models.CharField(max_length=9000)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=9000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grandprix',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9000)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'grandprix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raceresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastestlaptime', models.FloatField(blank=True, null=True)),
                ('grid', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9000, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('constructorid', models.IntegerField()),
            ],
            options={
                'db_table': 'raceresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driverinseason',
            fields=[
                ('number', models.IntegerField()),
                ('driverid', models.OneToOneField(db_column='driverid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='orf1.driver')),
            ],
            options={
                'db_table': 'driverinseason',
                'managed': False,
            },
        ),
    ]
